### ISSUE TITLE
Class Bmi has virtual member functions, but no virtual destructor

### ISSUE THREAD

**Issue by PhilMiller** [csdms/bmi-cxx#11]
Anything inheriting from the provided `Bmi` class and being referred to through that abstract base class will run afoul of an inability to properly destroy itself and its members.

Cf https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rh-dtor

**Comment by PhilMiller** [comment]
This results in compiler warnings such as this:

```
In file included from /Users/phil/Code/noaa/ngen/extern/test_bmi_cpp/src/test_bmi_cpp.cpp:6:
/Users/phil/Code/noaa/ngen/extern/test_bmi_cpp/include/test_bmi_cpp.hpp: In function 'void bmi_model_destroy(TestBmiCpp*)':
/Users/phil/Code/noaa/ngen/extern/test_bmi_cpp/include/test_bmi_cpp.hpp:275:17: warning: deleting object of polymorphic class type 'TestBmiCpp' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
  275 |                 delete ptr;
```

**Comment by aufdenkampe** [comment]
@mdpiper, I think merging PR #12 from @PhilMiller makes sense to me.

Although our team still haven't gotten far enough along with our BMI C++ work to have encountered an issue with not having a virtual destructor method, from my work with embedded C++ (in https://github.com/EnviroDIY/ModularSensors), I know that adding an virtual destructor method to every class is important, to be able to clear an instantiated object from memory. The syntax that @PhilMiller suggested is exactly the way we implement destructors in our code.

**Comment by mdpiper** [comment]
@aufdenkampe Thank you for your comment on this. I'll try to get things moving in the PR.
